version: "3.8"

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    environment:
      - WEBHOOK_URL=n8n-workflow-production.up.railway.app
      - N8N_SECURE_COOKIE=false
      - NODE_FUNCTION_ALLOW_EXTERNAL=cheerio
    command: sh -c "npm install cheerio && n8n start"
    restart: unless-stopped

volumes:
  n8n_data:
    external: true
